### ISSUE TITLE
此插件，不能适配taro.js

### ISSUE THREAD

**Issue by 729902288** [MellowCo/unplugin-unocss-attributify-wechat#1]
您好，由于taro v3.5x打包工具，目前还是webpack5。此插件只有vite版的，不能适用taro，能否增加一个webpack的支持？
配置及出错信息如下：
import transformWeClass from 'unplugin-transform-we-class/webpack';
import presetAttributifyWechat,{defaultAttributes} from 'unplugin-unocss-attributify-wechat/webpack'；

webpackChain(chain) {
      chain.plugin("transformWeClass").use(transformWeClass()); 
      chain.plugin('presetAttributifyWechat').use(presetAttributifyWechat());  
},

![image](https://user-images.githubusercontent.com/20468762/183544407-17dac88b-c293-419c-a6c3-1f5481841015.png)

**Comment by MellowCo** [comment]
import { defaultIgnoreNonValuedAttributes, presetAttributifyWechat } from 'unplugin-unocss-attributify-wechat/webpack'
我的，readme忘更新了
`uniapp` ,`taro` 使用文档，见 [github](https://github.com/MellowCo/unocss-preset-weapp) [掘金](https://juejin.cn/post/7116730180252467236/)
