### ISSUE TITLE
Used uniapp unplugin - attributify - to - class plug-ins using the failure

### ISSUE THREAD

**Issue by Soumns777** [MellowCo/unplugin-unocss-attributify-wechat#3]
I use in uniapp unocss, use the unplugin - attributify - to - class this plug-in hope to be able to achieve without writing style in the class, then is not effective, I had to in front of each style added a prefix, the result is effective, just I in unocss config. Ts set rules yield failure, want to ask next what can I do with my above the solution of this kind of circumstance? Thank you very much。

##### 💫  Vite.config.ts

```typescript
import { defineConfig } from 'vite';
import uni from '@dcloudio/vite-plugin-uni';
import {
  defaultAttributes,
  defaultIgnoreNonValuedAttributes,
  presetAttributifyWechat,
} from 'unplugin-unocss-attributify-wechat/vite';
import AutoImport from 'unplugin-auto-import/vite';
import setupExtend from 'vite-plugin-vue-setup-extend';
import UnoCSS from 'unocss/vite';
import { attributifyToClass } from 'unplugin-attributify-to-class/vite';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    uni(),
    presetAttributifyWechat({
      attributes: [...defaultAttributes],
      ignoreNonValuedAttributes: [...defaultIgnoreNonValuedAttributes],
    }),
    AutoImport({
      imports: ['uni-app', 'vue'],
      dts: 'src/auto-import.d.ts',
    }),
    setupExtend(),
    UnoCSS(),
    attributifyToClass({
      attributes: [...defaultAttributes],
    }),
  ],
});

```

##### 💫 Unocss.config.ts

```typescript
import presetWeapp from 'unocss-preset-weapp';
import { defineConfig } from 'unocss';
import {
  transformerAttributify,
  transformerClass,
} from 'unocss-preset-weapp/transformer';

export default defineConfig({
  presets: [
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp({
      // prefix: 'soumns-',
    }),
  ],
   rules: [
    [
      'soumns-flex',
      {
        'display': 'flex',
        'align-items': 'center',
        'justify-content': 'center',
        'box-sizing': 'border-box',
      },
     ],
  ],

  shortcuts: [ ],
  // v0.1.14 unplugin-attributify-to-class 和 unplugin-transform-class 内置到 transformer 中
  transformers: [
    // options 见https://github.com/MellowCo/unplugin-attributify-to-class
    transformerAttributify({
       nonValuedAttribute: true,
       classPrefix: 'soumns-',
    }),

    // options 见https://github.com/MellowCo/unplugin-transform-class
    transformerClass(),
  ],
});

```

##### 💫 Use

```vue
// There is  effective (if not use soumns-flex)
<view w200 h200 bg-green flex items-center justify-center text="red 40">
      Test
</view>

// There is  effective (if use soumns-flex)
<view w200 h200 bg-green soumns-flex text="red 40">
      Test
</view>

```

**Comment by Soumns777** [comment]
Above the second use soumns - flex does not take effect, the effective writing is to write wrong

**Comment by MellowCo** [comment]
* vite.config.ts
remove `unplugin-unocss-attributify-wechat` and `unplugin-attributify-to-class` , only use `transformerAttributify` is ok

```ts
import { defineConfig } from 'vite';
import uni from '@dcloudio/vite-plugin-uni';

import AutoImport from 'unplugin-auto-import/vite';
import setupExtend from 'vite-plugin-vue-setup-extend';
import UnoCSS from 'unocss/vite';


// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    uni(),
    AutoImport({
      imports: ['uni-app', 'vue'],
      dts: 'src/auto-import.d.ts',
    }),
    setupExtend(),
    UnoCSS(),
  ],
});
```

**Comment by MellowCo** [comment]
* flex 
Because you set `classPrefix: 'soumns-'` in `transformerAttributify`, it will be automatically spliced into the class
```html
<view w200 h200 bg-green flex text="red 40">
     Test
</view>
```
![image](https://user-images.githubusercontent.com/47939250/191895742-86eec5cb-8f7f-4805-a0bc-ef0552fec4b7.png)


* soumns-flex
so `soumns-flex` will transform to `soumns-soumns-flex`
![image](https://user-images.githubusercontent.com/47939250/191895755-af1cc241-62e6-4dbd-ad81-4729ad371da3.png)

**Comment by MellowCo** [comment]
if you want to use `soumns-flex`, not `flex`
you can remove `classPrefix: 'soumns-'` in `transformerAttributify`

```ts
transformerAttributify({
   nonValuedAttribute: true,
   // classPrefix: 'soumns-',
}),
```

![image](https://user-images.githubusercontent.com/47939250/191895674-3dd892f3-a4f6-409e-87cf-1ec39c0662c3.png)

**Comment by Soumns777** [comment]
Thank you very much, for the first time I use this thing, and not very skilled, is on the basis of online tutorials messed with, why don't I don't know the start is the main class inside the unocss patterns is not effective, led to the back of a series of problems, now think we should actually just open transformerAttributifyzhong nonValuedAttribute attributes, or thank you very much, also said a very Chen Ken word is hope the author can be used to document and tutorial greatly rich, this also is helpful for beginners to use these things, thanks。

**Comment by Soumns777** [comment]
The situation seemed to use unocss - preset - weapp transformerAttributify, temporarily I didn't understand what is the author of this plugin for, see trouble tell me just a little, thank you very much。

**Comment by MellowCo** [comment]
At the beginning, I developed the `unplugin-attributify-to-class` and `unplugin-transform-class` to solve the problem of miniprogram css. You need to download the `unplugin-attributify-to-class` , `unplugin-transform-class`  and `unocss-preset-weapp `at the same time

before `unocss-preset-weapp` v0.1.14 , need in `vite.config.ts` import `unplugin-transform-class/vite`, `unplugin-attributify-to-class/vite`, `unocss`,  
```ts
import { defineConfig } from 'vite'
import uni from '@dcloudio/vite-plugin-uni'
import Unocss from 'unocss/vite'
import transformWeClass from 'unplugin-transform-class/vite'
import { presetAttributifyWechat } from 'unplugin-attributify-to-class/vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    uni(),

    // https://github.com/MellowCo/unplugin-attributify-to-class
    presetAttributifyWechat(),

    // https://github.com/antfu/unocss
    Unocss(),

    // https://github.com/MellowCo/unplugin-transform-class
    transformWeClass(),
  ],
})
```

and set `unocss-preset-weapp` in `unocss.config.ts`, is too much
```ts
import presetWeapp from 'unocss-preset-weapp'
import { defineConfig } from 'unocss'

export default defineConfig({
  presets: [
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp(),
  ],
})
```

--- 

after  `unocss-preset-weapp` v0.1.14,  i put the core function of  `unplugin-transform-class` and `unplugin-attributify-to-class` in `unocss-preset-weapp/transformer `

now only install `unocss-preset-weapp`  package and set `transformer ` in `unocss-preset-weapp`

```ts
import { defineConfig } from 'vite'
import uni from '@dcloudio/vite-plugin-uni'
import Unocss from 'unocss/vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    uni(),

    // https://github.com/antfu/unocss
    Unocss(),
  ],
})
```
the transformer options same as `unplugin-transform-class` and `unplugin-attributify-to-class`
```ts
import presetWeapp from 'unocss-preset-weapp'
import { defineConfig } from 'unocss'
import { transformerAttributify, transformerClass } from 'unocss-preset-weapp/transformer'

export default defineConfig({
  presets: [
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp(),
  ],
  shortcuts: [
    {
      'border-base': 'border border-gray-500_10',
      'center': 'flex justify-center items-center',
    },
  ],

  // v0.1.14 unplugin-attributify-to-class 和 unplugin-transform-class 内置到 transformer 中
  transformers: [
    // options 见https://github.com/MellowCo/unplugin-attributify-to-class#options
    transformerAttributify(),

    // options 见https://github.com/MellowCo/unplugin-transform-class#options
    transformerClass(),
  ]
})
```

**Comment by Soumns777** [comment]
Really thank you can in spite of being very busy toglance answer to my question

**Comment by Soumns777** [comment]
I have a question, it is now as before in other vue project introduction of unocss background image is not effective?
 <view w72 h72 soumns-bg class="bg-[url(src/static/logo.png)]"> </view>
As I wrote above does not show the default icon。

**Comment by Soumns777** [comment]
<view w72 h72 soumns-bg class="bg-[url(src/static/logo.png)]"> </view>

**Comment by Soumns777** [comment]
```vue
 <template>
   <view w72 h72 soumns-bg class="bg-[url(src/static/logo.png)]"> </view>
 </template>
```

**Comment by Soumns777** [comment]
Like I this situation is to use the above the background image is not normal, but in other vue program can be normal display, I want to ask this is because the small program so you can't display normally?

**Comment by MellowCo** [comment]
Thank you for your feedback

**Comment by MellowCo** [comment]
fixed in `unocss-preset-weapp` latest

![image](https://user-images.githubusercontent.com/47939250/192081787-649ba619-9a1e-4ac7-aeba-5d0a27d82fe1.png)

but mini program not support local url

![image](https://user-images.githubusercontent.com/47939250/192081799-91754396-18bb-4752-abbf-da4ea818c936.png)

so need use `style` or `net url`

* style
```html
<view class="w-100 h-100 bg-cover mb-3" style="background-image: url(../../static/logo.png)" />
```

![image](https://user-images.githubusercontent.com/47939250/192081985-f7490b01-269a-471e-963e-91aed493102a.png)

* net url

``` html
 <view class="bg-[url(https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg)] bg-cover mb-3 w-100 h-100 " />
```
![image](https://user-images.githubusercontent.com/47939250/192081971-eacdaedd-71c6-4671-93fe-c474d03fc934.png)
